//Write XML
 private void DumpToXMLFile(List<Url> urls, string fileName)
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            settings.OmitXmlDeclaration = true;
            settings.NewLineOnAttributes = true;
            settings.ConformanceLevel = ConformanceLevel.Auto;

            using (XmlWriter writer = XmlWriter.Create(fileName, settings))
            {
                writer.WriteStartDocument();
                writer.WriteStartElement("Countries");
                foreach (var url in urls)
                {
                    writer.WriteStartElement("Country");
                        writer.WriteElementString("Name", url.Name);                        
                        writer.WriteElementString("Url", url.Uri);
                    writer.WriteEndElement();
                }
                writer.WriteEndElement();
                writer.WriteEndElement();                
            }
        }
--------------------------------------------------------------------------------
writer.WriteEndElement();
writer.WriteEndElement();
--------------------------------------------------------------------------------
writer.WriteStartDocument();
writer.WriteStartElement("Countries");
--------------------------------------------------------------------------------
XmlWriter writer = XmlWriter.Create(@"Products.xml", settings);

writer.WriteStartDocument();

writer.WriteComment("This file is generated by the program.");

writer.WriteStartElement("Books");
writer.WriteStartElement("Book");
writer.WriteAttributeString("ISBN", "0553212419");
writer.WriteElementString("Title", "Sherlock Holmes");
writer.WriteElementString("Author", "Sir Arthur Conan Doyle");
writer.WriteEndElement();
writer.WriteEndElement();
writer.WriteEndDocument();
writer.Flush();
writer.Close();
-----------------------------------------------
void WriteBookData(XmlWriter writer, string isbn, string title, string author)
{
    writer.WriteStartElement("Book");
    writer.WriteAttributeString("ISBN", isbn);
    writer.WriteElementString("Title", title);
    writer.WriteElementString("Author", author);
    writer.WriteEndElement();
}

XmlWriterSettings settings = new XmlWriterSettings();
settings.Indent = true;
using (XmlWriter writer = XmlWriter.Create(@"Products.xml", settings))
{
    writer.WriteStartDocument();

    writer.WriteComment("This file is generated by the program.");

    writer.WriteStartElement("Books");
    WriteBookData(writer, "0553212419", "Sherlock Holmes", "Sir Arthur Conan Doyle");
    writer.WriteEndElement();
    writer.WriteEndDocument();
    writer.Flush();
}
------------------------------------------------------
using System;
using System.Text;
using System.Xml;

namespace WritingXml
{
    class Program
    {
        static void Main(string[] args)
        {
            XmlWriter xmlWriter = XmlWriter.Create("test.xml");

            xmlWriter.WriteStartDocument();
            xmlWriter.WriteStartElement("users");

            xmlWriter.WriteStartElement("user");
            xmlWriter.WriteAttributeString("age", "42");
            xmlWriter.WriteString("John Doe");
            xmlWriter.WriteEndElement();

            xmlWriter.WriteStartElement("user");
            xmlWriter.WriteAttributeString("age", "39");
            xmlWriter.WriteString("Jane Doe");

            xmlWriter.WriteEndDocument();
            xmlWriter.Close();
        }
    }
}